---
  - name: Creating autoscaling groups
    hosts: localhost
    vars:
      constants:
        frankfurt: eu-central-1
        milano: eu-south-1
        key_name: Test
        key_name_m: KeyPair

    tasks:
        # Rcover information from files
        - name: recover ulixes id
          debug: var=item
          with_file:
            - "./ulixes"
          register: ulixes_id

        - name: recover ulixes security group
          debug: var=item
          with_file:
            - "./ulixes_sg"
          register: sg_ulixes

        - name: recover vpc id a
          debug: var=item
          with_file:
            - "./subnet_id_a"
          register: subnet_id_a

        - name: recover vpc id b
          debug: var=item
          with_file:
            - "./subnet_id_b"
          register: subnet_id_b

        - name: recover vpc id c
          debug: var=item
          with_file:
            - "./subnet_id_c"
          register: subnet_id_c

        - ec2_ami:
            instance_id: "{{ ulixes_id.results[0].item }}"
            state: present
            wait: yes
            name: ulixes_ami
          register: ulixes_ami

        #Launch configuration
        - ec2_lc:
            name: ulixes_lc
            image_id: "{{ ulixes_ami.image_id }}"
            key_name: "{{ constants.key_name }}"
            security_groups: ["{{ sg_ulixes.results[0].item }}"]
            instance_type: t2.micro
            assign_public_ip: yes
            volumes:
            - device_name: /dev/xvda
              volume_size: 8
              volume_type: gp2
              iops: 100
              delete_on_termination: true

        #Autoscaling
        - ec2_asg:
            name: ulixes_asg
            launch_config_name: ulixes_lc
            load_balancers: [ 'load-balancer-ulixes' ]
            availability_zones: [ "{{ constants.frankfurt }}a", "{{ constants.frankfurt }}b" , "{{ constants.frankfurt }}c"]
            health_check_period: 60
            health_check_type: ELB
            replace_all_instances: yes
            min_size: 2
            max_size: 5
            vpc_zone_identifier: ["{{ subnet_id_a.results[0].item }}", "{{ subnet_id_b.results[0].item }}" , "{{ subnet_id_c.results[0].item }}"]
            desired_capacity: 3
            region: "{{ constants.frankfurt }}"

