---
  - name: Creating Snapshots & configuring autoscaling
    hosts: localhost

    tasks:
      - name: Creating volume of Pythia server
        ec2_snapshot:
          volume_id: "{{lookup('file', './pythia') }}"
          snapshot_tags:
                vol: pythia

      - name: Creating volume of Ulixes server
        ec2_snapshot:
          volume_id: "{{lookup('file', './ulixes') }}"
          snapshot_tags:
                vol: ulixes

      - name: Creating volumesof Hermes server
        ec2_snapshot:
          volume_id: "{{lookup('file', './hermes') }}"
          snapshot_tags:
                vol: ulixes

      - name: Gathering info of volumes of Hermes server
        ec2_snapshot_info:
          filters:
            "tag:vol": pythia
        register: pythia_vol
        # acces id con pythia.volume_id

      - name: Gathering info of volumes of Hermes server
        ec2_snapshot_info:
          filters:
            "tag:vol": hermes
        register: hermes_vol

      - name: Gathering info of volumes of Ulixes server
        ec2_snapshot_info:
          filters:
            "tag:vol": ulixes
        register: ulixes_vol
