---
- hosts: web
  remote_user: ec2-user

  vars:
    remote_home: "/home/ec2-user"
    remote_app_dir: "{{remote_home}}/Ulixes"

  tasks:
    - name: download Git
      become: yes
      yum:
        name: git
        state: present

    - name: install python3
      become: yes # we need root privileges 
      yum:
        name: python3.x86_64
        state: present

    - name: install pip
      become: yes # we need root privileges 
      yum:
        name: python3-pip.noarch
        state: present

    - name: install required Python modules
      become: yes 
      pip:
        name: googlemaps
        executable: pip3

    - name: install required Python modules
      become: yes 
      pip:
        name: boto3
        executable: pip3

    - name: download Ulixes repository
      command: git clone https://github.com/UltraLe/Ulixes.git "{{ remote_app_dir }}"
      ignore_errors: yes

    - name: move service in correct folder
      become: yes
      command: cp "{{remote_app_dir}}"/ansible/ulixes.service /etc/systemd/system/

    - name: enable and start systemd service
      become: yes 
      systemd:
        daemon_reload: yes
        state: restarted
        name: "ulixes.service"
        enabled: yes

    - name: copy aws config file
      become: yes 
      copy:
        src: "../credentials.json"
        dest: "{{remote_app_dir}}/"

    - name: copy aws config file
      become: yes 
      copy:
        src: "../config.json"
        dest: "{{remote_app_dir}}/"

    - name: copy aws credentials file
      become: yes 
      copy:
        src: "../API_KEY.conf"
        dest: "{{remote_app_dir}}/"

    - name: start service
      become: yes
      command: systemctl daemon-reload

    - name: start service
      become: yes
      command: systemctl start ulixes.service

    - name: start service
      become: yes
      command: systemctl enable ulixes.service