---
- hosts: tag_server_pythia
  remote_user: ec2-user

  vars:
    remote_home: "/home/ec2-user"
    remote_app_dir: "{{remote_home}}/Pythia"

  tasks:
    - name: download Git
      become: yes
      yum:
        name: git
        state: present

    - name: install python3
      become: yes # we need root privileges
      yum:
        name: python3.x86_64
        state: present

    - name: install pip
      become: yes # we need root privileges
      yum:
        name: python3-pip.noarch
        state: present

    - name: download Pythia repository
      command: git clone --single-branch --branch FloodingMechanism https://github.com/UltraLe/Pythia.git "{{ remote_app_dir }}"
      ignore_errors: yes

    - name: move service in correct folder
      become: yes
      command: cp "{{remote_app_dir}}"/pythia.service /etc/systemd/system/

    - name: deamon reload services
      become: yes
      command:
        cmd: systemctl daemon-reload

    - name: start systemd service
      become: yes
      command:
        cmd: systemctl start pythia.service

    - name: enable systemd service
      become: yes
      command:
        cmd: systemctl enable pythia.service


    



